# Generated by Django 2.2.6 on 2019-10-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("WarUnicorn", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="unicorn", old_name="availaible", new_name="available"
        )
    ]
