# Generated by Django 2.2.6 on 2019-10-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("WarUnicorn", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="city"),
        migrations.RemoveField(model_name="userprofile", name="country"),
        migrations.RemoveField(model_name="userprofile", name="dob"),
        migrations.RemoveField(model_name="userprofile", name="title"),
        migrations.RemoveField(model_name="userprofile", name="zip"),
    ]
